* Org Manage

This is a module to help managing a large collection of org files. It
is based on [[https://github.com/yoshinari-nomura/org-octopress][org-octopress]] by Yoshinari Nomura.


** Introduction

Most of us have a large number of org files floating around. The idea
is that you get a simplified view of your org files in a single window
(think of it as a dashboard for your org-files). For example, this is
a hypothetical view created with org-manage.


| Date     | Title                  | Categories | Filename                   |
|----------+------------------------+------------+----------------------------|
| 13/05/29 | Cooking                | Hobbies    | /home/dmg/org/cooking.org  |
| 13/05/29 | Project X              | Research   | /home/dmg/org/x.org        |
| 13/05/29 | The different licenses | Research   | /home/dmg/org/licenses.org |
| 13/05/29 | Todo File              | todo       | /home/dmg/org/todo.org     |
| 13/05/28 | Linux                  | FAQs       | /home/dmg/org/linux.org    |
| 13/05/28 | Notes                  | Notes      | /home/dmg/org/notes.org    |

** How it works

org-manage scans a given directory (recursively) looking for org
files. For each, an entry is created. The title is extracted from the
attribute #+TITLE: in the org file. The category is extracted from the
first #+CATEGORY in the file (I suggest you add a default category to
each file.

** How to use it

Define the location where org files are to be found. Currently it only
supports one directory. You can solve this by creating symbolic links
from inside this directory to the locations of other org files. There
are other configuration variables (e.g. how much to recurse, files to
ignore, etc--see [[./org-manage.el][source code file of org-manage.el]].

#+BEGIN_SRC emacs_lisp
(setq org-manage-directory-org       "~/myorgfiles")
#+END_SRC

Then simply run it using:

#+BEGIN_SRC emacs_lisp
M-x org-manage
#+END_SRC

** Requirements

You need to install [[https://github.com/kiwanami][Masashi Sakurai]]'s ctable from https://github.com/kiwanami/emacs-ctable

** Comments 

If you have comments, patches or suggestions, please send them to me
at dmg <replacewiththattfamoussymbol> uvic.ca

--dmg




